attitude_estimation_plugin:
  plugin: "AttitudeEstimationPlugin"
  # Subscriber and Publisher topic names
  imu_topic: "/anymal/imu" # Unitree: "/trunk_imu" # ANYmal: "/sensors/imu"
  pub_topic: "attitude"

  # Attitude Estimation Parameters
  kp: 10.0
  ki: 0.02

  # Rotation Matrix from IMU frame to Base frame
  base_R_imu: [-1.0, 0.0, 0.0,
               0.0, 1.0, 0.0,
               0.0, 0.0, -1.0]
  # Fake-North Vector in Navigation Frame: it needs to be a constant vector
  north_vector: [0.577, 0.577, 0.577]

  # Gravity Vector in Navigation Frame
  gravity_vector: [0.0, 0.0, 9.81]

  # XKF Covariance Matrices
  P: [1.0e-12, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 1.0e-12, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 1.0e-12, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 1.0e-12, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 1.0e-12, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 1.0e-12]

  Q: [1.0e-15, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 1.0e-15, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 1.0e-15, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 1.0e-15, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 1.0e-15, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 1.0e-15]

  R: [1.0e-10, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 1.0e-10, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 1.0e-10, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 1.0e-10, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 1.0e-10, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 1.0e-10] 
