/**:
  ros__parameters:
    contact_data_packaging_plugin:
      plugin: "ContactDataPackagingPlugin"
      # Subscriber and Publisher topic names
      # LF: Left Front leg, RF: Right Front leg, LH: Left Hind leg, RH: Right Hind leg
      wrench_lf_topic: "/contact/fl" # Unitree: "/visual/FL_foot_contact/the_force" # ANYmal "/state_estimator/contact_force_lf_foot"
      wrench_rf_topic: "/contact/fr" # Unitree: "/visual/FR_foot_contact/the_force" # ANYmal "/state_estimator/contact_force_rf_foot"
      wrench_lh_topic: "/contact/fl" # Unitree: "/visual/RL_foot_contact/the_force" # ANYmal "/state_estimator/contact_force_lh_foot"
      wrench_rh_topic: "/contact/rr" # Unitree: "/visual/RR_foot_contact/the_force" # ANYmal "/state_estimator/contact_force_rh_foot"
    
      pub_topic: "contact_detection"