/**:
  ros__parameters:
    leg_odometry_plugin:
      plugin: "LegOdometryPlugin"
      # urdf_path: "$(find state_estimator)/urdfs/anymal.urdf"
      urdf_path: "$(find go2_description)/urdf/go2_description.urdf"

      imu_topic: "/imu" # Unitree: "/trunk_imu" # ANYmal: "/sensors/imu"
      joint_states_topic: "/joint_states" # Unitree (Go1): "/go1_gazebo/joint_states" # ANYmal: "/state_estimator/joint_states"
      contact_topic: "/state_estimator/contact_detection"
      attitude_topic: "/state_estimator/attitude"
      pub_topic: "/state_estimator/leg_odometry"
      base_height_topic: "/state_estimator/base_height"
      # Feet frame names (order: FL, FR, RL, RR)
      feet_frame_names: ["FL_foot", "FR_foot", "RL_foot", "RR_foot"]