// Generated by gencpp from file state_estimator_msgs/ContactDetection.msg
// DO NOT EDIT!


#ifndef STATE_ESTIMATOR_MSGS_MESSAGE_CONTACTDETECTION_H
#define STATE_ESTIMATOR_MSGS_MESSAGE_CONTACTDETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace state_estimator_msgs
{
template <class ContainerAllocator>
struct ContactDetection_
{
  typedef ContactDetection_<ContainerAllocator> Type;

  ContactDetection_()
    : header()
    , stance_lf(false)
    , stance_rf(false)
    , stance_lh(false)
    , stance_rh(false)  {
    }
  ContactDetection_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , stance_lf(false)
    , stance_rf(false)
    , stance_lh(false)
    , stance_rh(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _stance_lf_type;
  _stance_lf_type stance_lf;

   typedef uint8_t _stance_rf_type;
  _stance_rf_type stance_rf;

   typedef uint8_t _stance_lh_type;
  _stance_lh_type stance_lh;

   typedef uint8_t _stance_rh_type;
  _stance_rh_type stance_rh;





  typedef boost::shared_ptr< ::state_estimator_msgs::ContactDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::state_estimator_msgs::ContactDetection_<ContainerAllocator> const> ConstPtr;

}; // struct ContactDetection_

typedef ::state_estimator_msgs::ContactDetection_<std::allocator<void> > ContactDetection;

typedef boost::shared_ptr< ::state_estimator_msgs::ContactDetection > ContactDetectionPtr;
typedef boost::shared_ptr< ::state_estimator_msgs::ContactDetection const> ContactDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::state_estimator_msgs::ContactDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::state_estimator_msgs::ContactDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::state_estimator_msgs::ContactDetection_<ContainerAllocator1> & lhs, const ::state_estimator_msgs::ContactDetection_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.stance_lf == rhs.stance_lf &&
    lhs.stance_rf == rhs.stance_rf &&
    lhs.stance_lh == rhs.stance_lh &&
    lhs.stance_rh == rhs.stance_rh;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::state_estimator_msgs::ContactDetection_<ContainerAllocator1> & lhs, const ::state_estimator_msgs::ContactDetection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace state_estimator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::state_estimator_msgs::ContactDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::state_estimator_msgs::ContactDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_estimator_msgs::ContactDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_estimator_msgs::ContactDetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_estimator_msgs::ContactDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_estimator_msgs::ContactDetection_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::state_estimator_msgs::ContactDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "78b512adaaaa7714d41f42af63ebb35b";
  }

  static const char* value(const ::state_estimator_msgs::ContactDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x78b512adaaaa7714ULL;
  static const uint64_t static_value2 = 0xd41f42af63ebb35bULL;
};

template<class ContainerAllocator>
struct DataType< ::state_estimator_msgs::ContactDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "state_estimator_msgs/ContactDetection";
  }

  static const char* value(const ::state_estimator_msgs::ContactDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::state_estimator_msgs::ContactDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"bool stance_lf\n"
"bool stance_rf\n"
"bool stance_lh\n"
"bool stance_rh\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::state_estimator_msgs::ContactDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::state_estimator_msgs::ContactDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.stance_lf);
      stream.next(m.stance_rf);
      stream.next(m.stance_lh);
      stream.next(m.stance_rh);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ContactDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::state_estimator_msgs::ContactDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::state_estimator_msgs::ContactDetection_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "stance_lf: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stance_lf);
    s << indent << "stance_rf: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stance_rf);
    s << indent << "stance_lh: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stance_lh);
    s << indent << "stance_rh: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stance_rh);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STATE_ESTIMATOR_MSGS_MESSAGE_CONTACTDETECTION_H
