// Generated by gencpp from file state_estimator_msgs/SeActuatorState.msg
// DO NOT EDIT!


#ifndef STATE_ESTIMATOR_MSGS_MESSAGE_SEACTUATORSTATE_H
#define STATE_ESTIMATOR_MSGS_MESSAGE_SEACTUATORSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/Imu.h>

namespace state_estimator_msgs
{
template <class ContainerAllocator>
struct SeActuatorState_
{
  typedef SeActuatorState_<ContainerAllocator> Type;

  SeActuatorState_()
    : header()
    , name()
    , statusword(0)
    , current(0.0)
    , gear_position(0.0)
    , gear_velocity(0.0)
    , joint_position(0.0)
    , joint_velocity(0.0)
    , joint_acceleration(0.0)
    , joint_torque(0.0)
    , imu()  {
    }
  SeActuatorState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , name(_alloc)
    , statusword(0)
    , current(0.0)
    , gear_position(0.0)
    , gear_velocity(0.0)
    , joint_position(0.0)
    , joint_velocity(0.0)
    , joint_acceleration(0.0)
    , joint_torque(0.0)
    , imu(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef uint32_t _statusword_type;
  _statusword_type statusword;

   typedef double _current_type;
  _current_type current;

   typedef double _gear_position_type;
  _gear_position_type gear_position;

   typedef double _gear_velocity_type;
  _gear_velocity_type gear_velocity;

   typedef double _joint_position_type;
  _joint_position_type joint_position;

   typedef double _joint_velocity_type;
  _joint_velocity_type joint_velocity;

   typedef double _joint_acceleration_type;
  _joint_acceleration_type joint_acceleration;

   typedef double _joint_torque_type;
  _joint_torque_type joint_torque;

   typedef  ::sensor_msgs::Imu_<ContainerAllocator>  _imu_type;
  _imu_type imu;





  typedef boost::shared_ptr< ::state_estimator_msgs::SeActuatorState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::state_estimator_msgs::SeActuatorState_<ContainerAllocator> const> ConstPtr;

}; // struct SeActuatorState_

typedef ::state_estimator_msgs::SeActuatorState_<std::allocator<void> > SeActuatorState;

typedef boost::shared_ptr< ::state_estimator_msgs::SeActuatorState > SeActuatorStatePtr;
typedef boost::shared_ptr< ::state_estimator_msgs::SeActuatorState const> SeActuatorStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::state_estimator_msgs::SeActuatorState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::state_estimator_msgs::SeActuatorState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::state_estimator_msgs::SeActuatorState_<ContainerAllocator1> & lhs, const ::state_estimator_msgs::SeActuatorState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.name == rhs.name &&
    lhs.statusword == rhs.statusword &&
    lhs.current == rhs.current &&
    lhs.gear_position == rhs.gear_position &&
    lhs.gear_velocity == rhs.gear_velocity &&
    lhs.joint_position == rhs.joint_position &&
    lhs.joint_velocity == rhs.joint_velocity &&
    lhs.joint_acceleration == rhs.joint_acceleration &&
    lhs.joint_torque == rhs.joint_torque &&
    lhs.imu == rhs.imu;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::state_estimator_msgs::SeActuatorState_<ContainerAllocator1> & lhs, const ::state_estimator_msgs::SeActuatorState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace state_estimator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::state_estimator_msgs::SeActuatorState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::state_estimator_msgs::SeActuatorState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_estimator_msgs::SeActuatorState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_estimator_msgs::SeActuatorState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_estimator_msgs::SeActuatorState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_estimator_msgs::SeActuatorState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::state_estimator_msgs::SeActuatorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5beb885e629c734ee244b26cb1ffcc17";
  }

  static const char* value(const ::state_estimator_msgs::SeActuatorState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5beb885e629c734eULL;
  static const uint64_t static_value2 = 0xe244b26cb1ffcc17ULL;
};

template<class ContainerAllocator>
struct DataType< ::state_estimator_msgs::SeActuatorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "state_estimator_msgs/SeActuatorState";
  }

  static const char* value(const ::state_estimator_msgs::SeActuatorState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::state_estimator_msgs::SeActuatorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Series-elastic actuator state\n"
"\n"
"# Header of the message\n"
"Header header\n"
"# Name of the actuator\n"
"string name\n"
"# Statusword\n"
"uint32 statusword\n"
"# Motor current [A]\n"
"float64 current\n"
"# Position of the spring on the gear side [rad]\n"
"float64 gear_position\n"
"# Velocity of the spring on the gear side [rad/s]\n"
"float64 gear_velocity\n"
"# Position of the spring on the joint side [rad]\n"
"float64 joint_position\n"
"# Velocity of the spring on the joint side [rad/s]\n"
"float64 joint_velocity\n"
"# Acceleration of the spring on the joint side [rad/s^2]\n"
"float64 joint_acceleration\n"
"# Joint torque [Nm]\n"
"float64 joint_torque\n"
"# IMU measurement\n"
"sensor_msgs/Imu imu\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Imu\n"
"# This is a message to hold data from an IMU (Inertial Measurement Unit)\n"
"#\n"
"# Accelerations should be in m/s^2 (not in g's), and rotational velocity should be in rad/sec\n"
"#\n"
"# If the covariance of the measurement is known, it should be filled in (if all you know is the \n"
"# variance of each measurement, e.g. from the datasheet, just put those along the diagonal)\n"
"# A covariance matrix of all zeros will be interpreted as \"covariance unknown\", and to use the\n"
"# data a covariance will have to be assumed or gotten from some other source\n"
"#\n"
"# If you have no estimate for one of the data elements (e.g. your IMU doesn't produce an orientation \n"
"# estimate), please set element 0 of the associated covariance matrix to -1\n"
"# If you are interpreting this message, please check for a value of -1 in the first element of each \n"
"# covariance matrix, and disregard the associated estimate.\n"
"\n"
"Header header\n"
"\n"
"geometry_msgs/Quaternion orientation\n"
"float64[9] orientation_covariance # Row major about x, y, z axes\n"
"\n"
"geometry_msgs/Vector3 angular_velocity\n"
"float64[9] angular_velocity_covariance # Row major about x, y, z axes\n"
"\n"
"geometry_msgs/Vector3 linear_acceleration\n"
"float64[9] linear_acceleration_covariance # Row major x, y z \n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::state_estimator_msgs::SeActuatorState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::state_estimator_msgs::SeActuatorState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.name);
      stream.next(m.statusword);
      stream.next(m.current);
      stream.next(m.gear_position);
      stream.next(m.gear_velocity);
      stream.next(m.joint_position);
      stream.next(m.joint_velocity);
      stream.next(m.joint_acceleration);
      stream.next(m.joint_torque);
      stream.next(m.imu);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SeActuatorState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::state_estimator_msgs::SeActuatorState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::state_estimator_msgs::SeActuatorState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "statusword: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.statusword);
    s << indent << "current: ";
    Printer<double>::stream(s, indent + "  ", v.current);
    s << indent << "gear_position: ";
    Printer<double>::stream(s, indent + "  ", v.gear_position);
    s << indent << "gear_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.gear_velocity);
    s << indent << "joint_position: ";
    Printer<double>::stream(s, indent + "  ", v.joint_position);
    s << indent << "joint_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.joint_velocity);
    s << indent << "joint_acceleration: ";
    Printer<double>::stream(s, indent + "  ", v.joint_acceleration);
    s << indent << "joint_torque: ";
    Printer<double>::stream(s, indent + "  ", v.joint_torque);
    s << indent << "imu: ";
    s << std::endl;
    Printer< ::sensor_msgs::Imu_<ContainerAllocator> >::stream(s, indent + "  ", v.imu);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STATE_ESTIMATOR_MSGS_MESSAGE_SEACTUATORSTATE_H
