// Generated by gencpp from file state_estimator_msgs/SeActuatorReadings.msg
// DO NOT EDIT!


#ifndef STATE_ESTIMATOR_MSGS_MESSAGE_SEACTUATORREADINGS_H
#define STATE_ESTIMATOR_MSGS_MESSAGE_SEACTUATORREADINGS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <state_estimator_msgs/SeActuatorReading.h>

namespace state_estimator_msgs
{
template <class ContainerAllocator>
struct SeActuatorReadings_
{
  typedef SeActuatorReadings_<ContainerAllocator> Type;

  SeActuatorReadings_()
    : readings()  {
    }
  SeActuatorReadings_(const ContainerAllocator& _alloc)
    : readings(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::state_estimator_msgs::SeActuatorReading_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::state_estimator_msgs::SeActuatorReading_<ContainerAllocator> >> _readings_type;
  _readings_type readings;





  typedef boost::shared_ptr< ::state_estimator_msgs::SeActuatorReadings_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::state_estimator_msgs::SeActuatorReadings_<ContainerAllocator> const> ConstPtr;

}; // struct SeActuatorReadings_

typedef ::state_estimator_msgs::SeActuatorReadings_<std::allocator<void> > SeActuatorReadings;

typedef boost::shared_ptr< ::state_estimator_msgs::SeActuatorReadings > SeActuatorReadingsPtr;
typedef boost::shared_ptr< ::state_estimator_msgs::SeActuatorReadings const> SeActuatorReadingsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::state_estimator_msgs::SeActuatorReadings_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::state_estimator_msgs::SeActuatorReadings_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::state_estimator_msgs::SeActuatorReadings_<ContainerAllocator1> & lhs, const ::state_estimator_msgs::SeActuatorReadings_<ContainerAllocator2> & rhs)
{
  return lhs.readings == rhs.readings;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::state_estimator_msgs::SeActuatorReadings_<ContainerAllocator1> & lhs, const ::state_estimator_msgs::SeActuatorReadings_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace state_estimator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::state_estimator_msgs::SeActuatorReadings_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::state_estimator_msgs::SeActuatorReadings_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_estimator_msgs::SeActuatorReadings_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_estimator_msgs::SeActuatorReadings_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_estimator_msgs::SeActuatorReadings_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_estimator_msgs::SeActuatorReadings_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::state_estimator_msgs::SeActuatorReadings_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff6230194b1da4ad6213f9aae966106d";
  }

  static const char* value(const ::state_estimator_msgs::SeActuatorReadings_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff6230194b1da4adULL;
  static const uint64_t static_value2 = 0x6213f9aae966106dULL;
};

template<class ContainerAllocator>
struct DataType< ::state_estimator_msgs::SeActuatorReadings_<ContainerAllocator> >
{
  static const char* value()
  {
    return "state_estimator_msgs/SeActuatorReadings";
  }

  static const char* value(const ::state_estimator_msgs::SeActuatorReadings_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::state_estimator_msgs::SeActuatorReadings_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Series-elastic actuator readings\n"
"\n"
"SeActuatorReading[] readings\n"
"\n"
"================================================================================\n"
"MSG: state_estimator_msgs/SeActuatorReading\n"
"# Series-elastic actuator reading\n"
"#\n"
"Header header\n"
"# States\n"
"SeActuatorState state\n"
"# Set-points\n"
"SeActuatorCommand commanded\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: state_estimator_msgs/SeActuatorState\n"
"# Series-elastic actuator state\n"
"\n"
"# Header of the message\n"
"Header header\n"
"# Name of the actuator\n"
"string name\n"
"# Statusword\n"
"uint32 statusword\n"
"# Motor current [A]\n"
"float64 current\n"
"# Position of the spring on the gear side [rad]\n"
"float64 gear_position\n"
"# Velocity of the spring on the gear side [rad/s]\n"
"float64 gear_velocity\n"
"# Position of the spring on the joint side [rad]\n"
"float64 joint_position\n"
"# Velocity of the spring on the joint side [rad/s]\n"
"float64 joint_velocity\n"
"# Acceleration of the spring on the joint side [rad/s^2]\n"
"float64 joint_acceleration\n"
"# Joint torque [Nm]\n"
"float64 joint_torque\n"
"# IMU measurement\n"
"sensor_msgs/Imu imu\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Imu\n"
"# This is a message to hold data from an IMU (Inertial Measurement Unit)\n"
"#\n"
"# Accelerations should be in m/s^2 (not in g's), and rotational velocity should be in rad/sec\n"
"#\n"
"# If the covariance of the measurement is known, it should be filled in (if all you know is the \n"
"# variance of each measurement, e.g. from the datasheet, just put those along the diagonal)\n"
"# A covariance matrix of all zeros will be interpreted as \"covariance unknown\", and to use the\n"
"# data a covariance will have to be assumed or gotten from some other source\n"
"#\n"
"# If you have no estimate for one of the data elements (e.g. your IMU doesn't produce an orientation \n"
"# estimate), please set element 0 of the associated covariance matrix to -1\n"
"# If you are interpreting this message, please check for a value of -1 in the first element of each \n"
"# covariance matrix, and disregard the associated estimate.\n"
"\n"
"Header header\n"
"\n"
"geometry_msgs/Quaternion orientation\n"
"float64[9] orientation_covariance # Row major about x, y, z axes\n"
"\n"
"geometry_msgs/Vector3 angular_velocity\n"
"float64[9] angular_velocity_covariance # Row major about x, y, z axes\n"
"\n"
"geometry_msgs/Vector3 linear_acceleration\n"
"float64[9] linear_acceleration_covariance # Row major x, y z \n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: state_estimator_msgs/SeActuatorCommand\n"
"# Series-elastic actuator command\n"
"\n"
"Header header\n"
"# Name of the actuator\n"
"string name\n"
"# Control mode\n"
"int16 MODE_NA                                       = 0  # Not available\n"
"int16 MODE_FREEZE                                   = 1  # Freeze motor\n"
"int16 MODE_DISABLE                                  = 2  # Disable motor\n"
"int16 MODE_CURRENT                                  = 3  # Track current\n"
"int16 MODE_MOTOR_POSITION                           = 4  # Track motor position\n"
"int16 MODE_MOTOR_VELOCITY                           = 5  # Track motor velocity\n"
"int16 MODE_GEAR_POSITION                            = 6  # Track gear position\n"
"int16 MODE_GEAR_VELOCITY                            = 7  # Track gear velocity\n"
"int16 MODE_JOINT_POSITION                           = 8  # Track joint position\n"
"int16 MODE_JOINT_VELOCITY                           = 9  # Track joint velocity\n"
"int16 MODE_JOINT_TORQUE                             = 10 # Track joint torque\n"
"int16 MODE_JOINT_POSITION_VELOCITY                  = 11 # Track joint position with feedforward velocity\n"
"int16 MODE_JOINT_POSITION_VELOCITY_TORQUE           = 12 # Track joint position with feedforward velocity and torque\n"
"int16 MODE_JOINT_POSITION_VELOCITY_TORQUE_PID_GAINS = 13 # Track joint position with feedforward velocity and torque using custom joint position gains\n"
"int16 mode\n"
"# Motor current [A]\n"
"float64 current\n"
"# Position (motor/gear/joint) [rad]\n"
"float64 position\n"
"# Velocity (motor/gear/joint) [rad/s]\n"
"float64 velocity\n"
"# Torque (joint) [Nm]\n"
"float64 joint_torque\n"
"# Custom PID gains [-]\n"
"float32 pid_gains_p\n"
"float32 pid_gains_i\n"
"float32 pid_gains_d\n"
;
  }

  static const char* value(const ::state_estimator_msgs::SeActuatorReadings_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::state_estimator_msgs::SeActuatorReadings_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.readings);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SeActuatorReadings_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::state_estimator_msgs::SeActuatorReadings_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::state_estimator_msgs::SeActuatorReadings_<ContainerAllocator>& v)
  {
    s << indent << "readings[]" << std::endl;
    for (size_t i = 0; i < v.readings.size(); ++i)
    {
      s << indent << "  readings[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::state_estimator_msgs::SeActuatorReading_<ContainerAllocator> >::stream(s, indent + "    ", v.readings[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // STATE_ESTIMATOR_MSGS_MESSAGE_SEACTUATORREADINGS_H
