// Generated by gencpp from file state_estimator_msgs/AnymalState.msg
// DO NOT EDIT!


#ifndef STATE_ESTIMATOR_MSGS_MESSAGE_ANYMALSTATE_H
#define STATE_ESTIMATOR_MSGS_MESSAGE_ANYMALSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/TwistStamped.h>
#include <state_estimator_msgs/ExtendedJointState.h>
#include <state_estimator_msgs/Contact.h>
#include <geometry_msgs/TransformStamped.h>

namespace state_estimator_msgs
{
template <class ContainerAllocator>
struct AnymalState_
{
  typedef AnymalState_<ContainerAllocator> Type;

  AnymalState_()
    : header()
    , state(0)
    , pose()
    , twist()
    , joints()
    , contacts()
    , frame_transforms()  {
    }
  AnymalState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , state(0)
    , pose(_alloc)
    , twist(_alloc)
    , joints(_alloc)
    , contacts(_alloc)
    , frame_transforms(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _state_type;
  _state_type state;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef  ::geometry_msgs::TwistStamped_<ContainerAllocator>  _twist_type;
  _twist_type twist;

   typedef  ::state_estimator_msgs::ExtendedJointState_<ContainerAllocator>  _joints_type;
  _joints_type joints;

   typedef std::vector< ::state_estimator_msgs::Contact_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::state_estimator_msgs::Contact_<ContainerAllocator> >> _contacts_type;
  _contacts_type contacts;

   typedef std::vector< ::geometry_msgs::TransformStamped_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::TransformStamped_<ContainerAllocator> >> _frame_transforms_type;
  _frame_transforms_type frame_transforms;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(STATE_ERROR_SENSOR)
  #undef STATE_ERROR_SENSOR
#endif
#if defined(_WIN32) && defined(STATE_ERROR_ESTIMATOR)
  #undef STATE_ERROR_ESTIMATOR
#endif
#if defined(_WIN32) && defined(STATE_ERROR_UNKNOWN)
  #undef STATE_ERROR_UNKNOWN
#endif
#if defined(_WIN32) && defined(STATE_OK)
  #undef STATE_OK
#endif
#if defined(_WIN32) && defined(STATE_UNINITIALIZED)
  #undef STATE_UNINITIALIZED
#endif

  enum {
    STATE_ERROR_SENSOR = -3,
    STATE_ERROR_ESTIMATOR = -2,
    STATE_ERROR_UNKNOWN = -1,
    STATE_OK = 0,
    STATE_UNINITIALIZED = 1,
  };


  typedef boost::shared_ptr< ::state_estimator_msgs::AnymalState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::state_estimator_msgs::AnymalState_<ContainerAllocator> const> ConstPtr;

}; // struct AnymalState_

typedef ::state_estimator_msgs::AnymalState_<std::allocator<void> > AnymalState;

typedef boost::shared_ptr< ::state_estimator_msgs::AnymalState > AnymalStatePtr;
typedef boost::shared_ptr< ::state_estimator_msgs::AnymalState const> AnymalStateConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::state_estimator_msgs::AnymalState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::state_estimator_msgs::AnymalState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::state_estimator_msgs::AnymalState_<ContainerAllocator1> & lhs, const ::state_estimator_msgs::AnymalState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.state == rhs.state &&
    lhs.pose == rhs.pose &&
    lhs.twist == rhs.twist &&
    lhs.joints == rhs.joints &&
    lhs.contacts == rhs.contacts &&
    lhs.frame_transforms == rhs.frame_transforms;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::state_estimator_msgs::AnymalState_<ContainerAllocator1> & lhs, const ::state_estimator_msgs::AnymalState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace state_estimator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::state_estimator_msgs::AnymalState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::state_estimator_msgs::AnymalState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_estimator_msgs::AnymalState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_estimator_msgs::AnymalState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_estimator_msgs::AnymalState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_estimator_msgs::AnymalState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::state_estimator_msgs::AnymalState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1bee66925f9d04663ad1cd7f4a496f93";
  }

  static const char* value(const ::state_estimator_msgs::AnymalState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1bee66925f9d0466ULL;
  static const uint64_t static_value2 = 0x3ad1cd7f4a496f93ULL;
};

template<class ContainerAllocator>
struct DataType< ::state_estimator_msgs::AnymalState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "state_estimator_msgs/AnymalState";
  }

  static const char* value(const ::state_estimator_msgs::AnymalState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::state_estimator_msgs::AnymalState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Anymal state including generalized coordinates, velocities, and contacts.\n"
"std_msgs/Header header\n"
"\n"
"int8 STATE_ERROR_SENSOR=-3\n"
"int8 STATE_ERROR_ESTIMATOR=-2\n"
"int8 STATE_ERROR_UNKNOWN=-1\n"
"int8 STATE_OK=0\n"
"int8 STATE_UNINITIALIZED=1\n"
"int8 state\n"
"\n"
"# Position of the base with respect to the odom frame, and orientation from base to odom.\n"
"geometry_msgs/PoseStamped pose\n"
"\n"
"# Linear velocity and local angular velocity expressed in base frame.\n"
"geometry_msgs/TwistStamped twist\n"
"ExtendedJointState joints\n"
"Contact[] contacts\n"
"geometry_msgs/TransformStamped[] frame_transforms\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/TwistStamped\n"
"# A twist with reference coordinate frame and timestamp\n"
"Header header\n"
"Twist twist\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: state_estimator_msgs/ExtendedJointState\n"
"# sensor_msgs/JointState with an additional field for acceleration.\n"
"std_msgs/Header header\n"
"\n"
"string[] name\n"
"float64[] position\n"
"float64[] velocity\n"
"float64[] acceleration\n"
"float64[] effort\n"
"\n"
"================================================================================\n"
"MSG: state_estimator_msgs/Contact\n"
"# Contact definition.\n"
"uint8 STATE_OPEN=0\n"
"uint8 STATE_CLOSED=1\n"
"uint8 STATE_SLIPPING=2\n"
"\n"
"std_msgs/Header header\n"
"string name\n"
"uint8 state\n"
"geometry_msgs/Wrench wrench\n"
"geometry_msgs/Point position\n"
"geometry_msgs/Vector3 normal\n"
"float64 frictionCoefficient\n"
"float64 restitutionCoefficient\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Wrench\n"
"# This represents force in free space, separated into\n"
"# its linear and angular parts.\n"
"Vector3  force\n"
"Vector3  torque\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/TransformStamped\n"
"# This expresses a transform from coordinate frame header.frame_id\n"
"# to the coordinate frame child_frame_id\n"
"#\n"
"# This message is mostly used by the \n"
"# <a href=\"http://wiki.ros.org/tf\">tf</a> package. \n"
"# See its documentation for more information.\n"
"\n"
"Header header\n"
"string child_frame_id # the frame id of the child frame\n"
"Transform transform\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Transform\n"
"# This represents the transform between two coordinate frames in free space.\n"
"\n"
"Vector3 translation\n"
"Quaternion rotation\n"
;
  }

  static const char* value(const ::state_estimator_msgs::AnymalState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::state_estimator_msgs::AnymalState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.state);
      stream.next(m.pose);
      stream.next(m.twist);
      stream.next(m.joints);
      stream.next(m.contacts);
      stream.next(m.frame_transforms);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AnymalState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::state_estimator_msgs::AnymalState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::state_estimator_msgs::AnymalState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.state);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "twist: ";
    s << std::endl;
    Printer< ::geometry_msgs::TwistStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.twist);
    s << indent << "joints: ";
    s << std::endl;
    Printer< ::state_estimator_msgs::ExtendedJointState_<ContainerAllocator> >::stream(s, indent + "  ", v.joints);
    s << indent << "contacts[]" << std::endl;
    for (size_t i = 0; i < v.contacts.size(); ++i)
    {
      s << indent << "  contacts[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::state_estimator_msgs::Contact_<ContainerAllocator> >::stream(s, indent + "    ", v.contacts[i]);
    }
    s << indent << "frame_transforms[]" << std::endl;
    for (size_t i = 0; i < v.frame_transforms.size(); ++i)
    {
      s << indent << "  frame_transforms[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::TransformStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.frame_transforms[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // STATE_ESTIMATOR_MSGS_MESSAGE_ANYMALSTATE_H
