// Generated by gencpp from file state_estimator_msgs/SeActuatorStateExtended.msg
// DO NOT EDIT!


#ifndef STATE_ESTIMATOR_MSGS_MESSAGE_SEACTUATORSTATEEXTENDED_H
#define STATE_ESTIMATOR_MSGS_MESSAGE_SEACTUATORSTATEEXTENDED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/Imu.h>

namespace state_estimator_msgs
{
template <class ContainerAllocator>
struct SeActuatorStateExtended_
{
  typedef SeActuatorStateExtended_<ContainerAllocator> Type;

  SeActuatorStateExtended_()
    : header()
    , name()
    , statusword(0)
    , current(0.0)
    , gear_position(0.0)
    , gear_velocity(0.0)
    , joint_position(0.0)
    , joint_velocity(0.0)
    , joint_acceleration(0.0)
    , joint_torque(0.0)
    , imu()
    , motor_position(0.0)
    , motor_velocity(0.0)
    , gear_position_ticks(0)
    , joint_position_ticks(0)
    , temperature(0.0)
    , voltage(0.0)
    , timestamp(0)
    , desired_current_d(0.0)
    , measured_current_d(0.0)
    , desired_current_q(0.0)
    , measured_current_q(0.0)
    , measured_current_phase_u(0.0)
    , measured_voltage_phase_u(0.0)
    , measured_current_phase_v(0.0)
    , measured_voltage_phase_v(0.0)
    , measured_current_phase_w(0.0)
    , measured_voltage_phase_w(0.0)  {
    }
  SeActuatorStateExtended_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , name(_alloc)
    , statusword(0)
    , current(0.0)
    , gear_position(0.0)
    , gear_velocity(0.0)
    , joint_position(0.0)
    , joint_velocity(0.0)
    , joint_acceleration(0.0)
    , joint_torque(0.0)
    , imu(_alloc)
    , motor_position(0.0)
    , motor_velocity(0.0)
    , gear_position_ticks(0)
    , joint_position_ticks(0)
    , temperature(0.0)
    , voltage(0.0)
    , timestamp(0)
    , desired_current_d(0.0)
    , measured_current_d(0.0)
    , desired_current_q(0.0)
    , measured_current_q(0.0)
    , measured_current_phase_u(0.0)
    , measured_voltage_phase_u(0.0)
    , measured_current_phase_v(0.0)
    , measured_voltage_phase_v(0.0)
    , measured_current_phase_w(0.0)
    , measured_voltage_phase_w(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef uint32_t _statusword_type;
  _statusword_type statusword;

   typedef double _current_type;
  _current_type current;

   typedef double _gear_position_type;
  _gear_position_type gear_position;

   typedef double _gear_velocity_type;
  _gear_velocity_type gear_velocity;

   typedef double _joint_position_type;
  _joint_position_type joint_position;

   typedef double _joint_velocity_type;
  _joint_velocity_type joint_velocity;

   typedef double _joint_acceleration_type;
  _joint_acceleration_type joint_acceleration;

   typedef double _joint_torque_type;
  _joint_torque_type joint_torque;

   typedef  ::sensor_msgs::Imu_<ContainerAllocator>  _imu_type;
  _imu_type imu;

   typedef double _motor_position_type;
  _motor_position_type motor_position;

   typedef double _motor_velocity_type;
  _motor_velocity_type motor_velocity;

   typedef int32_t _gear_position_ticks_type;
  _gear_position_ticks_type gear_position_ticks;

   typedef int32_t _joint_position_ticks_type;
  _joint_position_ticks_type joint_position_ticks;

   typedef double _temperature_type;
  _temperature_type temperature;

   typedef double _voltage_type;
  _voltage_type voltage;

   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef double _desired_current_d_type;
  _desired_current_d_type desired_current_d;

   typedef double _measured_current_d_type;
  _measured_current_d_type measured_current_d;

   typedef double _desired_current_q_type;
  _desired_current_q_type desired_current_q;

   typedef double _measured_current_q_type;
  _measured_current_q_type measured_current_q;

   typedef double _measured_current_phase_u_type;
  _measured_current_phase_u_type measured_current_phase_u;

   typedef double _measured_voltage_phase_u_type;
  _measured_voltage_phase_u_type measured_voltage_phase_u;

   typedef double _measured_current_phase_v_type;
  _measured_current_phase_v_type measured_current_phase_v;

   typedef double _measured_voltage_phase_v_type;
  _measured_voltage_phase_v_type measured_voltage_phase_v;

   typedef double _measured_current_phase_w_type;
  _measured_current_phase_w_type measured_current_phase_w;

   typedef double _measured_voltage_phase_w_type;
  _measured_voltage_phase_w_type measured_voltage_phase_w;





  typedef boost::shared_ptr< ::state_estimator_msgs::SeActuatorStateExtended_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::state_estimator_msgs::SeActuatorStateExtended_<ContainerAllocator> const> ConstPtr;

}; // struct SeActuatorStateExtended_

typedef ::state_estimator_msgs::SeActuatorStateExtended_<std::allocator<void> > SeActuatorStateExtended;

typedef boost::shared_ptr< ::state_estimator_msgs::SeActuatorStateExtended > SeActuatorStateExtendedPtr;
typedef boost::shared_ptr< ::state_estimator_msgs::SeActuatorStateExtended const> SeActuatorStateExtendedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::state_estimator_msgs::SeActuatorStateExtended_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::state_estimator_msgs::SeActuatorStateExtended_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::state_estimator_msgs::SeActuatorStateExtended_<ContainerAllocator1> & lhs, const ::state_estimator_msgs::SeActuatorStateExtended_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.name == rhs.name &&
    lhs.statusword == rhs.statusword &&
    lhs.current == rhs.current &&
    lhs.gear_position == rhs.gear_position &&
    lhs.gear_velocity == rhs.gear_velocity &&
    lhs.joint_position == rhs.joint_position &&
    lhs.joint_velocity == rhs.joint_velocity &&
    lhs.joint_acceleration == rhs.joint_acceleration &&
    lhs.joint_torque == rhs.joint_torque &&
    lhs.imu == rhs.imu &&
    lhs.motor_position == rhs.motor_position &&
    lhs.motor_velocity == rhs.motor_velocity &&
    lhs.gear_position_ticks == rhs.gear_position_ticks &&
    lhs.joint_position_ticks == rhs.joint_position_ticks &&
    lhs.temperature == rhs.temperature &&
    lhs.voltage == rhs.voltage &&
    lhs.timestamp == rhs.timestamp &&
    lhs.desired_current_d == rhs.desired_current_d &&
    lhs.measured_current_d == rhs.measured_current_d &&
    lhs.desired_current_q == rhs.desired_current_q &&
    lhs.measured_current_q == rhs.measured_current_q &&
    lhs.measured_current_phase_u == rhs.measured_current_phase_u &&
    lhs.measured_voltage_phase_u == rhs.measured_voltage_phase_u &&
    lhs.measured_current_phase_v == rhs.measured_current_phase_v &&
    lhs.measured_voltage_phase_v == rhs.measured_voltage_phase_v &&
    lhs.measured_current_phase_w == rhs.measured_current_phase_w &&
    lhs.measured_voltage_phase_w == rhs.measured_voltage_phase_w;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::state_estimator_msgs::SeActuatorStateExtended_<ContainerAllocator1> & lhs, const ::state_estimator_msgs::SeActuatorStateExtended_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace state_estimator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::state_estimator_msgs::SeActuatorStateExtended_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::state_estimator_msgs::SeActuatorStateExtended_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_estimator_msgs::SeActuatorStateExtended_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_estimator_msgs::SeActuatorStateExtended_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_estimator_msgs::SeActuatorStateExtended_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_estimator_msgs::SeActuatorStateExtended_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::state_estimator_msgs::SeActuatorStateExtended_<ContainerAllocator> >
{
  static const char* value()
  {
    return "363d2497c1625484d8f3fe9fe046c107";
  }

  static const char* value(const ::state_estimator_msgs::SeActuatorStateExtended_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x363d2497c1625484ULL;
  static const uint64_t static_value2 = 0xd8f3fe9fe046c107ULL;
};

template<class ContainerAllocator>
struct DataType< ::state_estimator_msgs::SeActuatorStateExtended_<ContainerAllocator> >
{
  static const char* value()
  {
    return "state_estimator_msgs/SeActuatorStateExtended";
  }

  static const char* value(const ::state_estimator_msgs::SeActuatorStateExtended_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::state_estimator_msgs::SeActuatorStateExtended_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Series-elastic actuator extended state\n"
"\n"
"# Header of the message\n"
"Header header\n"
"# Name of the actuator\n"
"string name\n"
"# Statusword\n"
"uint32 statusword\n"
"# Motor current [A]\n"
"float64 current\n"
"# Position of the spring on the gear side [rad]\n"
"float64 gear_position\n"
"# Velocity of the spring on the gear side [rad/s]\n"
"float64 gear_velocity\n"
"# Position of the spring on the joint side [rad]\n"
"float64 joint_position\n"
"# Velocity of the spring on the joint side [rad/s]\n"
"float64 joint_velocity\n"
"# Acceleration of the spring on the joint side [rad/s^2]\n"
"float64 joint_acceleration\n"
"# Joint torque [Nm]\n"
"float64 joint_torque\n"
"# IMU measurement\n"
"sensor_msgs/Imu imu\n"
"\n"
"# Extended state data:\n"
"\n"
"# Position of the motor [rad]\n"
"float64 motor_position\n"
"# Velocity of the motor [rad/s]\n"
"float64 motor_velocity\n"
"# Position of the spring on the gear side [ticks]\n"
"int32 gear_position_ticks\n"
"# Position of the spring on the joint side [ticks]\n"
"int32 joint_position_ticks\n"
"# Temperature of the actuator [deg C]\n"
"float64 temperature\n"
"# Voltage [V]\n"
"float64 voltage\n"
"# Timestamp\n"
"uint64 timestamp\n"
"# Desired current d part\n"
"float64 desired_current_d\n"
"# Measured current d part\n"
"float64 measured_current_d\n"
"# Desired current q part\n"
"float64 desired_current_q\n"
"# Measured current q part\n"
"float64 measured_current_q\n"
"# Measured current phase u\n"
"float64 measured_current_phase_u\n"
"# Measured voltage phase u\n"
"float64 measured_voltage_phase_u\n"
"# Measured current phase v\n"
"float64 measured_current_phase_v\n"
"# Measured voltage phase v\n"
"float64 measured_voltage_phase_v\n"
"# Measured current phase w\n"
"float64 measured_current_phase_w\n"
"# Measured voltage phase w\n"
"float64 measured_voltage_phase_w\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Imu\n"
"# This is a message to hold data from an IMU (Inertial Measurement Unit)\n"
"#\n"
"# Accelerations should be in m/s^2 (not in g's), and rotational velocity should be in rad/sec\n"
"#\n"
"# If the covariance of the measurement is known, it should be filled in (if all you know is the \n"
"# variance of each measurement, e.g. from the datasheet, just put those along the diagonal)\n"
"# A covariance matrix of all zeros will be interpreted as \"covariance unknown\", and to use the\n"
"# data a covariance will have to be assumed or gotten from some other source\n"
"#\n"
"# If you have no estimate for one of the data elements (e.g. your IMU doesn't produce an orientation \n"
"# estimate), please set element 0 of the associated covariance matrix to -1\n"
"# If you are interpreting this message, please check for a value of -1 in the first element of each \n"
"# covariance matrix, and disregard the associated estimate.\n"
"\n"
"Header header\n"
"\n"
"geometry_msgs/Quaternion orientation\n"
"float64[9] orientation_covariance # Row major about x, y, z axes\n"
"\n"
"geometry_msgs/Vector3 angular_velocity\n"
"float64[9] angular_velocity_covariance # Row major about x, y, z axes\n"
"\n"
"geometry_msgs/Vector3 linear_acceleration\n"
"float64[9] linear_acceleration_covariance # Row major x, y z \n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::state_estimator_msgs::SeActuatorStateExtended_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::state_estimator_msgs::SeActuatorStateExtended_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.name);
      stream.next(m.statusword);
      stream.next(m.current);
      stream.next(m.gear_position);
      stream.next(m.gear_velocity);
      stream.next(m.joint_position);
      stream.next(m.joint_velocity);
      stream.next(m.joint_acceleration);
      stream.next(m.joint_torque);
      stream.next(m.imu);
      stream.next(m.motor_position);
      stream.next(m.motor_velocity);
      stream.next(m.gear_position_ticks);
      stream.next(m.joint_position_ticks);
      stream.next(m.temperature);
      stream.next(m.voltage);
      stream.next(m.timestamp);
      stream.next(m.desired_current_d);
      stream.next(m.measured_current_d);
      stream.next(m.desired_current_q);
      stream.next(m.measured_current_q);
      stream.next(m.measured_current_phase_u);
      stream.next(m.measured_voltage_phase_u);
      stream.next(m.measured_current_phase_v);
      stream.next(m.measured_voltage_phase_v);
      stream.next(m.measured_current_phase_w);
      stream.next(m.measured_voltage_phase_w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SeActuatorStateExtended_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::state_estimator_msgs::SeActuatorStateExtended_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::state_estimator_msgs::SeActuatorStateExtended_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "statusword: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.statusword);
    s << indent << "current: ";
    Printer<double>::stream(s, indent + "  ", v.current);
    s << indent << "gear_position: ";
    Printer<double>::stream(s, indent + "  ", v.gear_position);
    s << indent << "gear_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.gear_velocity);
    s << indent << "joint_position: ";
    Printer<double>::stream(s, indent + "  ", v.joint_position);
    s << indent << "joint_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.joint_velocity);
    s << indent << "joint_acceleration: ";
    Printer<double>::stream(s, indent + "  ", v.joint_acceleration);
    s << indent << "joint_torque: ";
    Printer<double>::stream(s, indent + "  ", v.joint_torque);
    s << indent << "imu: ";
    s << std::endl;
    Printer< ::sensor_msgs::Imu_<ContainerAllocator> >::stream(s, indent + "  ", v.imu);
    s << indent << "motor_position: ";
    Printer<double>::stream(s, indent + "  ", v.motor_position);
    s << indent << "motor_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.motor_velocity);
    s << indent << "gear_position_ticks: ";
    Printer<int32_t>::stream(s, indent + "  ", v.gear_position_ticks);
    s << indent << "joint_position_ticks: ";
    Printer<int32_t>::stream(s, indent + "  ", v.joint_position_ticks);
    s << indent << "temperature: ";
    Printer<double>::stream(s, indent + "  ", v.temperature);
    s << indent << "voltage: ";
    Printer<double>::stream(s, indent + "  ", v.voltage);
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    s << indent << "desired_current_d: ";
    Printer<double>::stream(s, indent + "  ", v.desired_current_d);
    s << indent << "measured_current_d: ";
    Printer<double>::stream(s, indent + "  ", v.measured_current_d);
    s << indent << "desired_current_q: ";
    Printer<double>::stream(s, indent + "  ", v.desired_current_q);
    s << indent << "measured_current_q: ";
    Printer<double>::stream(s, indent + "  ", v.measured_current_q);
    s << indent << "measured_current_phase_u: ";
    Printer<double>::stream(s, indent + "  ", v.measured_current_phase_u);
    s << indent << "measured_voltage_phase_u: ";
    Printer<double>::stream(s, indent + "  ", v.measured_voltage_phase_u);
    s << indent << "measured_current_phase_v: ";
    Printer<double>::stream(s, indent + "  ", v.measured_current_phase_v);
    s << indent << "measured_voltage_phase_v: ";
    Printer<double>::stream(s, indent + "  ", v.measured_voltage_phase_v);
    s << indent << "measured_current_phase_w: ";
    Printer<double>::stream(s, indent + "  ", v.measured_current_phase_w);
    s << indent << "measured_voltage_phase_w: ";
    Printer<double>::stream(s, indent + "  ", v.measured_voltage_phase_w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STATE_ESTIMATOR_MSGS_MESSAGE_SEACTUATORSTATEEXTENDED_H
