// Generated by gencpp from file state_estimator_msgs/SeActuatorReadingExtended.msg
// DO NOT EDIT!


#ifndef STATE_ESTIMATOR_MSGS_MESSAGE_SEACTUATORREADINGEXTENDED_H
#define STATE_ESTIMATOR_MSGS_MESSAGE_SEACTUATORREADINGEXTENDED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <state_estimator_msgs/SeActuatorStateExtended.h>
#include <state_estimator_msgs/SeActuatorCommand.h>

namespace state_estimator_msgs
{
template <class ContainerAllocator>
struct SeActuatorReadingExtended_
{
  typedef SeActuatorReadingExtended_<ContainerAllocator> Type;

  SeActuatorReadingExtended_()
    : header()
    , state()
    , commanded()  {
    }
  SeActuatorReadingExtended_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , state(_alloc)
    , commanded(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::state_estimator_msgs::SeActuatorStateExtended_<ContainerAllocator>  _state_type;
  _state_type state;

   typedef  ::state_estimator_msgs::SeActuatorCommand_<ContainerAllocator>  _commanded_type;
  _commanded_type commanded;





  typedef boost::shared_ptr< ::state_estimator_msgs::SeActuatorReadingExtended_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::state_estimator_msgs::SeActuatorReadingExtended_<ContainerAllocator> const> ConstPtr;

}; // struct SeActuatorReadingExtended_

typedef ::state_estimator_msgs::SeActuatorReadingExtended_<std::allocator<void> > SeActuatorReadingExtended;

typedef boost::shared_ptr< ::state_estimator_msgs::SeActuatorReadingExtended > SeActuatorReadingExtendedPtr;
typedef boost::shared_ptr< ::state_estimator_msgs::SeActuatorReadingExtended const> SeActuatorReadingExtendedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::state_estimator_msgs::SeActuatorReadingExtended_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::state_estimator_msgs::SeActuatorReadingExtended_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::state_estimator_msgs::SeActuatorReadingExtended_<ContainerAllocator1> & lhs, const ::state_estimator_msgs::SeActuatorReadingExtended_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.state == rhs.state &&
    lhs.commanded == rhs.commanded;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::state_estimator_msgs::SeActuatorReadingExtended_<ContainerAllocator1> & lhs, const ::state_estimator_msgs::SeActuatorReadingExtended_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace state_estimator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::state_estimator_msgs::SeActuatorReadingExtended_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::state_estimator_msgs::SeActuatorReadingExtended_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_estimator_msgs::SeActuatorReadingExtended_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_estimator_msgs::SeActuatorReadingExtended_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_estimator_msgs::SeActuatorReadingExtended_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_estimator_msgs::SeActuatorReadingExtended_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::state_estimator_msgs::SeActuatorReadingExtended_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ac9d8edf0f7d237de154004238775b6";
  }

  static const char* value(const ::state_estimator_msgs::SeActuatorReadingExtended_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ac9d8edf0f7d237ULL;
  static const uint64_t static_value2 = 0xde154004238775b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::state_estimator_msgs::SeActuatorReadingExtended_<ContainerAllocator> >
{
  static const char* value()
  {
    return "state_estimator_msgs/SeActuatorReadingExtended";
  }

  static const char* value(const ::state_estimator_msgs::SeActuatorReadingExtended_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::state_estimator_msgs::SeActuatorReadingExtended_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Series-elastic actuator extended reading\n"
"#\n"
"Header header\n"
"# States\n"
"SeActuatorStateExtended state\n"
"# Set-points\n"
"SeActuatorCommand commanded\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: state_estimator_msgs/SeActuatorStateExtended\n"
"# Series-elastic actuator extended state\n"
"\n"
"# Header of the message\n"
"Header header\n"
"# Name of the actuator\n"
"string name\n"
"# Statusword\n"
"uint32 statusword\n"
"# Motor current [A]\n"
"float64 current\n"
"# Position of the spring on the gear side [rad]\n"
"float64 gear_position\n"
"# Velocity of the spring on the gear side [rad/s]\n"
"float64 gear_velocity\n"
"# Position of the spring on the joint side [rad]\n"
"float64 joint_position\n"
"# Velocity of the spring on the joint side [rad/s]\n"
"float64 joint_velocity\n"
"# Acceleration of the spring on the joint side [rad/s^2]\n"
"float64 joint_acceleration\n"
"# Joint torque [Nm]\n"
"float64 joint_torque\n"
"# IMU measurement\n"
"sensor_msgs/Imu imu\n"
"\n"
"# Extended state data:\n"
"\n"
"# Position of the motor [rad]\n"
"float64 motor_position\n"
"# Velocity of the motor [rad/s]\n"
"float64 motor_velocity\n"
"# Position of the spring on the gear side [ticks]\n"
"int32 gear_position_ticks\n"
"# Position of the spring on the joint side [ticks]\n"
"int32 joint_position_ticks\n"
"# Temperature of the actuator [deg C]\n"
"float64 temperature\n"
"# Voltage [V]\n"
"float64 voltage\n"
"# Timestamp\n"
"uint64 timestamp\n"
"# Desired current d part\n"
"float64 desired_current_d\n"
"# Measured current d part\n"
"float64 measured_current_d\n"
"# Desired current q part\n"
"float64 desired_current_q\n"
"# Measured current q part\n"
"float64 measured_current_q\n"
"# Measured current phase u\n"
"float64 measured_current_phase_u\n"
"# Measured voltage phase u\n"
"float64 measured_voltage_phase_u\n"
"# Measured current phase v\n"
"float64 measured_current_phase_v\n"
"# Measured voltage phase v\n"
"float64 measured_voltage_phase_v\n"
"# Measured current phase w\n"
"float64 measured_current_phase_w\n"
"# Measured voltage phase w\n"
"float64 measured_voltage_phase_w\n"
"\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Imu\n"
"# This is a message to hold data from an IMU (Inertial Measurement Unit)\n"
"#\n"
"# Accelerations should be in m/s^2 (not in g's), and rotational velocity should be in rad/sec\n"
"#\n"
"# If the covariance of the measurement is known, it should be filled in (if all you know is the \n"
"# variance of each measurement, e.g. from the datasheet, just put those along the diagonal)\n"
"# A covariance matrix of all zeros will be interpreted as \"covariance unknown\", and to use the\n"
"# data a covariance will have to be assumed or gotten from some other source\n"
"#\n"
"# If you have no estimate for one of the data elements (e.g. your IMU doesn't produce an orientation \n"
"# estimate), please set element 0 of the associated covariance matrix to -1\n"
"# If you are interpreting this message, please check for a value of -1 in the first element of each \n"
"# covariance matrix, and disregard the associated estimate.\n"
"\n"
"Header header\n"
"\n"
"geometry_msgs/Quaternion orientation\n"
"float64[9] orientation_covariance # Row major about x, y, z axes\n"
"\n"
"geometry_msgs/Vector3 angular_velocity\n"
"float64[9] angular_velocity_covariance # Row major about x, y, z axes\n"
"\n"
"geometry_msgs/Vector3 linear_acceleration\n"
"float64[9] linear_acceleration_covariance # Row major x, y z \n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: state_estimator_msgs/SeActuatorCommand\n"
"# Series-elastic actuator command\n"
"\n"
"Header header\n"
"# Name of the actuator\n"
"string name\n"
"# Control mode\n"
"int16 MODE_NA                                       = 0  # Not available\n"
"int16 MODE_FREEZE                                   = 1  # Freeze motor\n"
"int16 MODE_DISABLE                                  = 2  # Disable motor\n"
"int16 MODE_CURRENT                                  = 3  # Track current\n"
"int16 MODE_MOTOR_POSITION                           = 4  # Track motor position\n"
"int16 MODE_MOTOR_VELOCITY                           = 5  # Track motor velocity\n"
"int16 MODE_GEAR_POSITION                            = 6  # Track gear position\n"
"int16 MODE_GEAR_VELOCITY                            = 7  # Track gear velocity\n"
"int16 MODE_JOINT_POSITION                           = 8  # Track joint position\n"
"int16 MODE_JOINT_VELOCITY                           = 9  # Track joint velocity\n"
"int16 MODE_JOINT_TORQUE                             = 10 # Track joint torque\n"
"int16 MODE_JOINT_POSITION_VELOCITY                  = 11 # Track joint position with feedforward velocity\n"
"int16 MODE_JOINT_POSITION_VELOCITY_TORQUE           = 12 # Track joint position with feedforward velocity and torque\n"
"int16 MODE_JOINT_POSITION_VELOCITY_TORQUE_PID_GAINS = 13 # Track joint position with feedforward velocity and torque using custom joint position gains\n"
"int16 mode\n"
"# Motor current [A]\n"
"float64 current\n"
"# Position (motor/gear/joint) [rad]\n"
"float64 position\n"
"# Velocity (motor/gear/joint) [rad/s]\n"
"float64 velocity\n"
"# Torque (joint) [Nm]\n"
"float64 joint_torque\n"
"# Custom PID gains [-]\n"
"float32 pid_gains_p\n"
"float32 pid_gains_i\n"
"float32 pid_gains_d\n"
;
  }

  static const char* value(const ::state_estimator_msgs::SeActuatorReadingExtended_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::state_estimator_msgs::SeActuatorReadingExtended_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.state);
      stream.next(m.commanded);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SeActuatorReadingExtended_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::state_estimator_msgs::SeActuatorReadingExtended_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::state_estimator_msgs::SeActuatorReadingExtended_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "state: ";
    s << std::endl;
    Printer< ::state_estimator_msgs::SeActuatorStateExtended_<ContainerAllocator> >::stream(s, indent + "  ", v.state);
    s << indent << "commanded: ";
    s << std::endl;
    Printer< ::state_estimator_msgs::SeActuatorCommand_<ContainerAllocator> >::stream(s, indent + "  ", v.commanded);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STATE_ESTIMATOR_MSGS_MESSAGE_SEACTUATORREADINGEXTENDED_H
