// Generated by gencpp from file series_elastic_actuator_msgs/SeActuatorCommand.msg
// DO NOT EDIT!


#ifndef SERIES_ELASTIC_ACTUATOR_MSGS_MESSAGE_SEACTUATORCOMMAND_H
#define SERIES_ELASTIC_ACTUATOR_MSGS_MESSAGE_SEACTUATORCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace series_elastic_actuator_msgs
{
template <class ContainerAllocator>
struct SeActuatorCommand_
{
  typedef SeActuatorCommand_<ContainerAllocator> Type;

  SeActuatorCommand_()
    : header()
    , name()
    , mode(0)
    , current(0.0)
    , position(0.0)
    , velocity(0.0)
    , joint_torque(0.0)
    , pid_gains_p(0.0)
    , pid_gains_i(0.0)
    , pid_gains_d(0.0)  {
    }
  SeActuatorCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , name(_alloc)
    , mode(0)
    , current(0.0)
    , position(0.0)
    , velocity(0.0)
    , joint_torque(0.0)
    , pid_gains_p(0.0)
    , pid_gains_i(0.0)
    , pid_gains_d(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef int16_t _mode_type;
  _mode_type mode;

   typedef double _current_type;
  _current_type current;

   typedef double _position_type;
  _position_type position;

   typedef double _velocity_type;
  _velocity_type velocity;

   typedef double _joint_torque_type;
  _joint_torque_type joint_torque;

   typedef float _pid_gains_p_type;
  _pid_gains_p_type pid_gains_p;

   typedef float _pid_gains_i_type;
  _pid_gains_i_type pid_gains_i;

   typedef float _pid_gains_d_type;
  _pid_gains_d_type pid_gains_d;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(MODE_NA)
  #undef MODE_NA
#endif
#if defined(_WIN32) && defined(MODE_FREEZE)
  #undef MODE_FREEZE
#endif
#if defined(_WIN32) && defined(MODE_DISABLE)
  #undef MODE_DISABLE
#endif
#if defined(_WIN32) && defined(MODE_CURRENT)
  #undef MODE_CURRENT
#endif
#if defined(_WIN32) && defined(MODE_MOTOR_POSITION)
  #undef MODE_MOTOR_POSITION
#endif
#if defined(_WIN32) && defined(MODE_MOTOR_VELOCITY)
  #undef MODE_MOTOR_VELOCITY
#endif
#if defined(_WIN32) && defined(MODE_GEAR_POSITION)
  #undef MODE_GEAR_POSITION
#endif
#if defined(_WIN32) && defined(MODE_GEAR_VELOCITY)
  #undef MODE_GEAR_VELOCITY
#endif
#if defined(_WIN32) && defined(MODE_JOINT_POSITION)
  #undef MODE_JOINT_POSITION
#endif
#if defined(_WIN32) && defined(MODE_JOINT_VELOCITY)
  #undef MODE_JOINT_VELOCITY
#endif
#if defined(_WIN32) && defined(MODE_JOINT_TORQUE)
  #undef MODE_JOINT_TORQUE
#endif
#if defined(_WIN32) && defined(MODE_JOINT_POSITION_VELOCITY)
  #undef MODE_JOINT_POSITION_VELOCITY
#endif
#if defined(_WIN32) && defined(MODE_JOINT_POSITION_VELOCITY_TORQUE)
  #undef MODE_JOINT_POSITION_VELOCITY_TORQUE
#endif
#if defined(_WIN32) && defined(MODE_JOINT_POSITION_VELOCITY_TORQUE_PID_GAINS)
  #undef MODE_JOINT_POSITION_VELOCITY_TORQUE_PID_GAINS
#endif

  enum {
    MODE_NA = 0,
    MODE_FREEZE = 1,
    MODE_DISABLE = 2,
    MODE_CURRENT = 3,
    MODE_MOTOR_POSITION = 4,
    MODE_MOTOR_VELOCITY = 5,
    MODE_GEAR_POSITION = 6,
    MODE_GEAR_VELOCITY = 7,
    MODE_JOINT_POSITION = 8,
    MODE_JOINT_VELOCITY = 9,
    MODE_JOINT_TORQUE = 10,
    MODE_JOINT_POSITION_VELOCITY = 11,
    MODE_JOINT_POSITION_VELOCITY_TORQUE = 12,
    MODE_JOINT_POSITION_VELOCITY_TORQUE_PID_GAINS = 13,
  };


  typedef boost::shared_ptr< ::series_elastic_actuator_msgs::SeActuatorCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::series_elastic_actuator_msgs::SeActuatorCommand_<ContainerAllocator> const> ConstPtr;

}; // struct SeActuatorCommand_

typedef ::series_elastic_actuator_msgs::SeActuatorCommand_<std::allocator<void> > SeActuatorCommand;

typedef boost::shared_ptr< ::series_elastic_actuator_msgs::SeActuatorCommand > SeActuatorCommandPtr;
typedef boost::shared_ptr< ::series_elastic_actuator_msgs::SeActuatorCommand const> SeActuatorCommandConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::series_elastic_actuator_msgs::SeActuatorCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::series_elastic_actuator_msgs::SeActuatorCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::series_elastic_actuator_msgs::SeActuatorCommand_<ContainerAllocator1> & lhs, const ::series_elastic_actuator_msgs::SeActuatorCommand_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.name == rhs.name &&
    lhs.mode == rhs.mode &&
    lhs.current == rhs.current &&
    lhs.position == rhs.position &&
    lhs.velocity == rhs.velocity &&
    lhs.joint_torque == rhs.joint_torque &&
    lhs.pid_gains_p == rhs.pid_gains_p &&
    lhs.pid_gains_i == rhs.pid_gains_i &&
    lhs.pid_gains_d == rhs.pid_gains_d;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::series_elastic_actuator_msgs::SeActuatorCommand_<ContainerAllocator1> & lhs, const ::series_elastic_actuator_msgs::SeActuatorCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace series_elastic_actuator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::series_elastic_actuator_msgs::SeActuatorCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::series_elastic_actuator_msgs::SeActuatorCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::series_elastic_actuator_msgs::SeActuatorCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::series_elastic_actuator_msgs::SeActuatorCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::series_elastic_actuator_msgs::SeActuatorCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::series_elastic_actuator_msgs::SeActuatorCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::series_elastic_actuator_msgs::SeActuatorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "99caa130fb942b20d4b16f18464e90d2";
  }

  static const char* value(const ::series_elastic_actuator_msgs::SeActuatorCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x99caa130fb942b20ULL;
  static const uint64_t static_value2 = 0xd4b16f18464e90d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::series_elastic_actuator_msgs::SeActuatorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "series_elastic_actuator_msgs/SeActuatorCommand";
  }

  static const char* value(const ::series_elastic_actuator_msgs::SeActuatorCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::series_elastic_actuator_msgs::SeActuatorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Series-elastic actuator command\n"
"\n"
"Header header\n"
"# Name of the actuator\n"
"string name\n"
"# Control mode\n"
"int16 MODE_NA                                       = 0  # Not available\n"
"int16 MODE_FREEZE                                   = 1  # Freeze motor\n"
"int16 MODE_DISABLE                                  = 2  # Disable motor\n"
"int16 MODE_CURRENT                                  = 3  # Track current\n"
"int16 MODE_MOTOR_POSITION                           = 4  # Track motor position\n"
"int16 MODE_MOTOR_VELOCITY                           = 5  # Track motor velocity\n"
"int16 MODE_GEAR_POSITION                            = 6  # Track gear position\n"
"int16 MODE_GEAR_VELOCITY                            = 7  # Track gear velocity\n"
"int16 MODE_JOINT_POSITION                           = 8  # Track joint position\n"
"int16 MODE_JOINT_VELOCITY                           = 9  # Track joint velocity\n"
"int16 MODE_JOINT_TORQUE                             = 10 # Track joint torque\n"
"int16 MODE_JOINT_POSITION_VELOCITY                  = 11 # Track joint position with feedforward velocity\n"
"int16 MODE_JOINT_POSITION_VELOCITY_TORQUE           = 12 # Track joint position with feedforward velocity and torque\n"
"int16 MODE_JOINT_POSITION_VELOCITY_TORQUE_PID_GAINS = 13 # Track joint position with feedforward velocity and torque using custom joint position gains\n"
"int16 mode\n"
"# Motor current [A]\n"
"float64 current\n"
"# Position (motor/gear/joint) [rad]\n"
"float64 position\n"
"# Velocity (motor/gear/joint) [rad/s]\n"
"float64 velocity\n"
"# Torque (joint) [Nm]\n"
"float64 joint_torque\n"
"# Custom PID gains [-]\n"
"float32 pid_gains_p\n"
"float32 pid_gains_i\n"
"float32 pid_gains_d\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::series_elastic_actuator_msgs::SeActuatorCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::series_elastic_actuator_msgs::SeActuatorCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.name);
      stream.next(m.mode);
      stream.next(m.current);
      stream.next(m.position);
      stream.next(m.velocity);
      stream.next(m.joint_torque);
      stream.next(m.pid_gains_p);
      stream.next(m.pid_gains_i);
      stream.next(m.pid_gains_d);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SeActuatorCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::series_elastic_actuator_msgs::SeActuatorCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::series_elastic_actuator_msgs::SeActuatorCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "mode: ";
    Printer<int16_t>::stream(s, indent + "  ", v.mode);
    s << indent << "current: ";
    Printer<double>::stream(s, indent + "  ", v.current);
    s << indent << "position: ";
    Printer<double>::stream(s, indent + "  ", v.position);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
    s << indent << "joint_torque: ";
    Printer<double>::stream(s, indent + "  ", v.joint_torque);
    s << indent << "pid_gains_p: ";
    Printer<float>::stream(s, indent + "  ", v.pid_gains_p);
    s << indent << "pid_gains_i: ";
    Printer<float>::stream(s, indent + "  ", v.pid_gains_i);
    s << indent << "pid_gains_d: ";
    Printer<float>::stream(s, indent + "  ", v.pid_gains_d);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIES_ELASTIC_ACTUATOR_MSGS_MESSAGE_SEACTUATORCOMMAND_H
