// Generated by gencpp from file series_elastic_actuator_msgs/SeActuatorCommands.msg
// DO NOT EDIT!


#ifndef SERIES_ELASTIC_ACTUATOR_MSGS_MESSAGE_SEACTUATORCOMMANDS_H
#define SERIES_ELASTIC_ACTUATOR_MSGS_MESSAGE_SEACTUATORCOMMANDS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <series_elastic_actuator_msgs/SeActuatorCommand.h>

namespace series_elastic_actuator_msgs
{
template <class ContainerAllocator>
struct SeActuatorCommands_
{
  typedef SeActuatorCommands_<ContainerAllocator> Type;

  SeActuatorCommands_()
    : commands()  {
    }
  SeActuatorCommands_(const ContainerAllocator& _alloc)
    : commands(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::series_elastic_actuator_msgs::SeActuatorCommand_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::series_elastic_actuator_msgs::SeActuatorCommand_<ContainerAllocator> >> _commands_type;
  _commands_type commands;





  typedef boost::shared_ptr< ::series_elastic_actuator_msgs::SeActuatorCommands_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::series_elastic_actuator_msgs::SeActuatorCommands_<ContainerAllocator> const> ConstPtr;

}; // struct SeActuatorCommands_

typedef ::series_elastic_actuator_msgs::SeActuatorCommands_<std::allocator<void> > SeActuatorCommands;

typedef boost::shared_ptr< ::series_elastic_actuator_msgs::SeActuatorCommands > SeActuatorCommandsPtr;
typedef boost::shared_ptr< ::series_elastic_actuator_msgs::SeActuatorCommands const> SeActuatorCommandsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::series_elastic_actuator_msgs::SeActuatorCommands_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::series_elastic_actuator_msgs::SeActuatorCommands_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::series_elastic_actuator_msgs::SeActuatorCommands_<ContainerAllocator1> & lhs, const ::series_elastic_actuator_msgs::SeActuatorCommands_<ContainerAllocator2> & rhs)
{
  return lhs.commands == rhs.commands;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::series_elastic_actuator_msgs::SeActuatorCommands_<ContainerAllocator1> & lhs, const ::series_elastic_actuator_msgs::SeActuatorCommands_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace series_elastic_actuator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::series_elastic_actuator_msgs::SeActuatorCommands_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::series_elastic_actuator_msgs::SeActuatorCommands_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::series_elastic_actuator_msgs::SeActuatorCommands_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::series_elastic_actuator_msgs::SeActuatorCommands_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::series_elastic_actuator_msgs::SeActuatorCommands_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::series_elastic_actuator_msgs::SeActuatorCommands_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::series_elastic_actuator_msgs::SeActuatorCommands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8bac105afcdb07f69773e72515936600";
  }

  static const char* value(const ::series_elastic_actuator_msgs::SeActuatorCommands_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8bac105afcdb07f6ULL;
  static const uint64_t static_value2 = 0x9773e72515936600ULL;
};

template<class ContainerAllocator>
struct DataType< ::series_elastic_actuator_msgs::SeActuatorCommands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "series_elastic_actuator_msgs/SeActuatorCommands";
  }

  static const char* value(const ::series_elastic_actuator_msgs::SeActuatorCommands_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::series_elastic_actuator_msgs::SeActuatorCommands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Series-elastic actuator commands\n"
"\n"
"SeActuatorCommand[] commands\n"
"\n"
"================================================================================\n"
"MSG: series_elastic_actuator_msgs/SeActuatorCommand\n"
"# Series-elastic actuator command\n"
"\n"
"Header header\n"
"# Name of the actuator\n"
"string name\n"
"# Control mode\n"
"int16 MODE_NA                                       = 0  # Not available\n"
"int16 MODE_FREEZE                                   = 1  # Freeze motor\n"
"int16 MODE_DISABLE                                  = 2  # Disable motor\n"
"int16 MODE_CURRENT                                  = 3  # Track current\n"
"int16 MODE_MOTOR_POSITION                           = 4  # Track motor position\n"
"int16 MODE_MOTOR_VELOCITY                           = 5  # Track motor velocity\n"
"int16 MODE_GEAR_POSITION                            = 6  # Track gear position\n"
"int16 MODE_GEAR_VELOCITY                            = 7  # Track gear velocity\n"
"int16 MODE_JOINT_POSITION                           = 8  # Track joint position\n"
"int16 MODE_JOINT_VELOCITY                           = 9  # Track joint velocity\n"
"int16 MODE_JOINT_TORQUE                             = 10 # Track joint torque\n"
"int16 MODE_JOINT_POSITION_VELOCITY                  = 11 # Track joint position with feedforward velocity\n"
"int16 MODE_JOINT_POSITION_VELOCITY_TORQUE           = 12 # Track joint position with feedforward velocity and torque\n"
"int16 MODE_JOINT_POSITION_VELOCITY_TORQUE_PID_GAINS = 13 # Track joint position with feedforward velocity and torque using custom joint position gains\n"
"int16 mode\n"
"# Motor current [A]\n"
"float64 current\n"
"# Position (motor/gear/joint) [rad]\n"
"float64 position\n"
"# Velocity (motor/gear/joint) [rad/s]\n"
"float64 velocity\n"
"# Torque (joint) [Nm]\n"
"float64 joint_torque\n"
"# Custom PID gains [-]\n"
"float32 pid_gains_p\n"
"float32 pid_gains_i\n"
"float32 pid_gains_d\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::series_elastic_actuator_msgs::SeActuatorCommands_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::series_elastic_actuator_msgs::SeActuatorCommands_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.commands);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SeActuatorCommands_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::series_elastic_actuator_msgs::SeActuatorCommands_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::series_elastic_actuator_msgs::SeActuatorCommands_<ContainerAllocator>& v)
  {
    s << indent << "commands[]" << std::endl;
    for (size_t i = 0; i < v.commands.size(); ++i)
    {
      s << indent << "  commands[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::series_elastic_actuator_msgs::SeActuatorCommand_<ContainerAllocator> >::stream(s, indent + "    ", v.commands[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIES_ELASTIC_ACTUATOR_MSGS_MESSAGE_SEACTUATORCOMMANDS_H
