// Generated by gencpp from file anymal_msgs/Contact.msg
// DO NOT EDIT!


#ifndef ANYMAL_MSGS_MESSAGE_CONTACT_H
#define ANYMAL_MSGS_MESSAGE_CONTACT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Wrench.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>

namespace anymal_msgs
{
template <class ContainerAllocator>
struct Contact_
{
  typedef Contact_<ContainerAllocator> Type;

  Contact_()
    : header()
    , name()
    , state(0)
    , wrench()
    , position()
    , normal()
    , frictionCoefficient(0.0)
    , restitutionCoefficient(0.0)  {
    }
  Contact_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , name(_alloc)
    , state(0)
    , wrench(_alloc)
    , position(_alloc)
    , normal(_alloc)
    , frictionCoefficient(0.0)
    , restitutionCoefficient(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef uint8_t _state_type;
  _state_type state;

   typedef  ::geometry_msgs::Wrench_<ContainerAllocator>  _wrench_type;
  _wrench_type wrench;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _normal_type;
  _normal_type normal;

   typedef double _frictionCoefficient_type;
  _frictionCoefficient_type frictionCoefficient;

   typedef double _restitutionCoefficient_type;
  _restitutionCoefficient_type restitutionCoefficient;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(STATE_OPEN)
  #undef STATE_OPEN
#endif
#if defined(_WIN32) && defined(STATE_CLOSED)
  #undef STATE_CLOSED
#endif
#if defined(_WIN32) && defined(STATE_SLIPPING)
  #undef STATE_SLIPPING
#endif

  enum {
    STATE_OPEN = 0u,
    STATE_CLOSED = 1u,
    STATE_SLIPPING = 2u,
  };


  typedef boost::shared_ptr< ::anymal_msgs::Contact_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::anymal_msgs::Contact_<ContainerAllocator> const> ConstPtr;

}; // struct Contact_

typedef ::anymal_msgs::Contact_<std::allocator<void> > Contact;

typedef boost::shared_ptr< ::anymal_msgs::Contact > ContactPtr;
typedef boost::shared_ptr< ::anymal_msgs::Contact const> ContactConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::anymal_msgs::Contact_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::anymal_msgs::Contact_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::anymal_msgs::Contact_<ContainerAllocator1> & lhs, const ::anymal_msgs::Contact_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.name == rhs.name &&
    lhs.state == rhs.state &&
    lhs.wrench == rhs.wrench &&
    lhs.position == rhs.position &&
    lhs.normal == rhs.normal &&
    lhs.frictionCoefficient == rhs.frictionCoefficient &&
    lhs.restitutionCoefficient == rhs.restitutionCoefficient;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::anymal_msgs::Contact_<ContainerAllocator1> & lhs, const ::anymal_msgs::Contact_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace anymal_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::anymal_msgs::Contact_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::anymal_msgs::Contact_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anymal_msgs::Contact_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anymal_msgs::Contact_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anymal_msgs::Contact_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anymal_msgs::Contact_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::anymal_msgs::Contact_<ContainerAllocator> >
{
  static const char* value()
  {
    return "48c55012030000155d5ac40f7586c2e6";
  }

  static const char* value(const ::anymal_msgs::Contact_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x48c5501203000015ULL;
  static const uint64_t static_value2 = 0x5d5ac40f7586c2e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::anymal_msgs::Contact_<ContainerAllocator> >
{
  static const char* value()
  {
    return "anymal_msgs/Contact";
  }

  static const char* value(const ::anymal_msgs::Contact_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::anymal_msgs::Contact_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Contact definition.\n"
"uint8 STATE_OPEN=0\n"
"uint8 STATE_CLOSED=1\n"
"uint8 STATE_SLIPPING=2\n"
"\n"
"std_msgs/Header header\n"
"string name\n"
"uint8 state\n"
"geometry_msgs/Wrench wrench\n"
"geometry_msgs/Point position\n"
"geometry_msgs/Vector3 normal\n"
"float64 frictionCoefficient\n"
"float64 restitutionCoefficient\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Wrench\n"
"# This represents force in free space, separated into\n"
"# its linear and angular parts.\n"
"Vector3  force\n"
"Vector3  torque\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::anymal_msgs::Contact_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::anymal_msgs::Contact_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.name);
      stream.next(m.state);
      stream.next(m.wrench);
      stream.next(m.position);
      stream.next(m.normal);
      stream.next(m.frictionCoefficient);
      stream.next(m.restitutionCoefficient);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Contact_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::anymal_msgs::Contact_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::anymal_msgs::Contact_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
    s << indent << "wrench: ";
    s << std::endl;
    Printer< ::geometry_msgs::Wrench_<ContainerAllocator> >::stream(s, indent + "  ", v.wrench);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "normal: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.normal);
    s << indent << "frictionCoefficient: ";
    Printer<double>::stream(s, indent + "  ", v.frictionCoefficient);
    s << indent << "restitutionCoefficient: ";
    Printer<double>::stream(s, indent + "  ", v.restitutionCoefficient);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ANYMAL_MSGS_MESSAGE_CONTACT_H
